# Tensorflow2.0 小练习

In [2]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [3]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########

    # 将输入转换为TensorFlow张量，确保数据类型为float32
    x = tf.cast(x, tf.float32)

    # 计算指数
    exp_x = tf.exp(x)

    # 计算最后一维的指数和，用于归一化
    # 最后一维通常是属于某个类别的概率，对其进行归一化
    sum_exp_x = tf.reduce_sum(exp_x, axis=-1, keepdims=True)

    # 计算softmax概率：每个元素的指数值除以指数和
    prob_x = exp_x / sum_exp_x

    return prob_x

#测试数据，来自随机正态分布
test_data = np.random.normal(size=[10, 5]).astype(np.float32)
print(test_data)
print(softmax(test_data).numpy())
#比较softmax函数的结果是否与tf.nn.softmax函数的结果一致
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

[[ 0.7522302  -0.05871538 -0.3995748   1.4157422  -0.05660807]
 [-0.20385897  1.3567791   0.19437975 -0.04637642  0.13372248]
 [-0.016101   -0.57322943  2.3795023  -0.8478688  -0.70687836]
 [ 1.9659184   1.6274889  -0.2850514   1.556407   -0.74753094]
 [ 0.5989454  -1.785647    1.4455488  -0.95527136 -1.2994574 ]
 [ 0.7322035  -0.5830047   1.963724   -0.9338021  -0.4387086 ]
 [ 0.05598401  0.5450637  -0.9637479  -0.12449894 -0.41151586]
 [ 1.0257028   0.89750886 -0.8318968  -1.5604948  -0.1657166 ]
 [ 1.1550524  -1.385352    0.7867837  -0.3040725   1.0288265 ]
 [ 1.1559253  -1.4780195   0.2581899   0.36149567 -1.1963102 ]]
[[0.2411104  0.10715853 0.07620674 0.46813974 0.10738458]
 [0.10180011 0.4847577  0.15160067 0.11916316 0.14267832]
 [0.07416123 0.04248339 0.81390595 0.03228084 0.03716859]
 [0.3923926  0.27973235 0.04131778 0.2605387  0.02601865]
 [0.2642006  0.02433988 0.6160401  0.05584009 0.03957928]
 [0.1925321  0.05167916 0.6596989  0.03638867 0.05970113]
 [0.22457077 0.366233

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [4]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    
    # 将输入转换为TensorFlow张量，确保数据类型为float32
    x = tf.cast(x, tf.float32)

    #sigmoid(x) = 1 / (1 + exp(-x))
    prob_x = 1.0 / (1.0 + tf.exp(-x))

    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [7]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    
    # x 为概率分布（已 softmax），label 为 one-hot 或概率标签
    x = tf.cast(x, tf.float32)
    label = tf.cast(label, tf.float32)

    # 交叉熵： -sum(label * log(x))
    #ce_per_example 为每个样本的交叉熵损失
    ce_per_example = -tf.reduce_sum(label * tf.math.log(x), axis=-1)
    # 对每个样本的交叉熵损失取均值，得到 batch 平均损失
    loss = tf.reduce_mean(ce_per_example)

    return loss

test_data = np.random.normal(size=[10, 5]).astype(np.float32)
prob = tf.nn.softmax(test_data)
# 生成 one-hot 标签
label = np.zeros_like(test_data, dtype=np.float32)
label[np.arange(10), np.random.randint(0, 5, size=10)] = 1.0

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

np.True_

## 实现 sigmoid 交叉熵loss函数

In [9]:
def sigmoid_ce(x, label):
    ##########
    '''实现 sigmoid 交叉熵loss函数， 不允许用tf自带的sigmoid_cross_entropy函数'''
    ##########
    # x 为概率 ŷ ∈ (0,1)，label ∈ [0,1]（可为0/1或概率）
    x = tf.cast(x, tf.float32)
    label = tf.cast(label, tf.float32)

    # 概率版二元交叉熵：L = -[ y*log(ŷ) + (1-y)*log(1-ŷ) ]
    ce = -(label * tf.math.log(x) + (1.0 - label) * tf.math.log(1.0 - x))

    # 若最后一维为类别维（多标签），按最后一维求和得到每样本损失；否则直接视为每样本损失
    ce_per_example = tf.reduce_sum(ce, axis=-1) if len(ce.shape) > 1 else ce

    # 对 batch 取均值，得到标量损失
    loss = tf.reduce_mean(ce_per_example)
    return loss

test_data = np.random.normal(size=[10]).astype(np.float32)
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(np.float32)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data)) - sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 1. 0. 1. 1. 0. 0. 0. 1. 1.]


np.True_